# Generated by Django 3.1.4 on 2021-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
